#!/bin/sh

SESSION=`basename $PWD`
COMMAND=$1

# create session
tmux -2 new-session -d -s $SESSION

# ----------------------- Main window -----------------------------------

# rename main window
tmux rename-window -t $SESSION:1 workspace

# split and resize panes on main
tmux split-window
tmux select-pane -t 1
tmux resize-pane -D 14
tmux select-pane -t 2
tmux split-window -h


# run processes

tmux select-window -t $SESSION:1

# run VIM
tmux select-pane -t 1
tmux send-keys 'nvim .' C-m

# run rails c
tmux select-pane -t 2
tmux send-keys 'rails c' C-m


# ========================================================================

#------------------------ Processes --------------------------------------

# create processes window, create panes
tmux new-window -t $SESSION -a -n processes

tmux split-window -h
tmux split-window -v
tmux select-pane -t 1
tmux split-window -v


# processes

# run rails s
tmux select-window -t $SESSION:2
tmux select-pane -t 1
tmux send-keys 'rails s' C-m

# run services in docker
tmux select-window -t $SESSION:2
tmux select-pane -t 3
#tmux send-keys 'docker-compose -f ./docker-compose.services.yml -p services up' C-m

# run sidekiq
tmux select-pane -t 2
tmux send-keys 'sidekiq' C-m

# run arg command
tmux select-pane -t 4
tmux send-keys "$COMMAND" C-m


# ========================================================================

# ------------------------- Manual ---------------------------------------

# create third window (manual)
tmux new-window -t $SESSION -a -n manual

tmux split-window -h
tmux split-window -v
tmux select-pane -t 1
tmux split-window -v

# processes
tmux select-window -t $SESSION:3

tmux select-pane -t 1
# tmux send-keys 'rspec' C-m


# ========================================================================

# ------------------------- Random ---------------------------------------

# create third window (manual)
tmux new-window -t $SESSION -a -n random

tmux split-window -h
tmux select-pane -t 1
tmux send-keys 'nvim ../reminders/random' C-m
tmux select-pane -t 2
tmux send-keys 'nvim ../reminders/branches' C-m

# processes
tmux select-window -t $SESSION:4

tmux select-pane -t 1
# tmux send-keys 'rspec' C-m


# ========================================================================


# select window and attach to session

tmux select-window -t $SESSION:1
tmux select-pane -t 1
tmux a -t $SESSION


