#!/bin/sh

git config --global alias.ck checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.df diff
git config --global alias.rb rebase
